spring:
  application:
    name: LogStore

  config:
    import: "optional:file:.env[.properties]"


management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

tablet:
  base-dir: data/logstore/
  total-tablets: 10